### ISSUE TITLE
Dockerized MongoDB for local development

### ISSUE THREAD

**Issue by riboney** [webdev-20/shorti-url-shortener#102]
**WHAT**
- Add  `./server/docker-compose.yml` that can be used to run a local dockerized instance of MongoDB for development & testing

**WHY**
- Provides an alternative, convenient method for using MongoDB

**HOW**
- It would be similar to this:
![image](https://user-images.githubusercontent.com/14286113/201902797-9b912b34-9626-4fe6-8e7c-d167ec851af2.png)

**Comment by cherylli** [comment]
if we add something like this is there an option to not use docker? or will docker be required to run the project locally?

**Comment by riboney** [comment]
> if we add something like this is there an option to not use docker? or will docker be required to run the project locally?

it will not affect the current project at all. Its like an optional `package.json` file that can be executed via the command `docker compose up` to run the mongodb instance. No need to run it if not using docker. It won't affect anyone's local setup

**Comment by cherylli** [comment]
yeah that sounds good

**Comment by riboney** [comment]
Sure thing
