### ISSUE TITLE
Documentation: Update Readme

### ISSUE THREAD

**Issue by cherylli** [webdev-20/shorti-url-shortener#21]
To include new name and stuff, it looks pretty outdated and not so professional

Suggestion: Find a nice readme.md template and apply it to our readme file

assigned to blanketmanatee

**Comment by cherylli** [comment]
Are you still working on it? @blanketmanatee

**Comment by EleekaN** [comment]
Hi @cherylli , it's new to me however I would like to try. Can you provide more details or any source I can refer to?

**Comment by cherylli** [comment]
I've already assigned this issue to myself. Normally, if an issue is assigned to someone they will work on it. But I guess you can do this one.

Using a readme template, e.g. https://github.com/othneildrew/Best-README-Template

**Comment by EleekaN** [comment]
Thank you... I came across one template which I will use. Could you share some more details of the project? Anything that can help me, get more insight.

**Comment by EleekaN** [comment]
I was checking out **readme.so**
Or you want me to try out the one you shared earlier.
Okay for the project details , let me go through the repository then and I will get back if there are any more questions.

**Comment by cherylli** [comment]
yeah that looks ok

**Comment by EleekaN** [comment]
@cherylli do you have license details and what can I put under features?

**Comment by cherylli** [comment]
license can be MIT for now
yeah maybe just put a link to the issues with the todo features, since i'll be updating that file
