### ISSUE TITLE
Add Auth Documentation to Swagger

### ISSUE THREAD

**Issue by cherylli** [webdev-20/shorti-url-shortener#58]
**Task**

new endpoints which needs to be added to swagger (api/docs)
register and login
/api/users/signup
/api/users/login

**More about the task (optional)**
server/docs.yaml

This might be useful
https://editor.swagger.io/

**Comment by buutw23** [comment]
Hi @cherylli , I would like to contribute, can I get more details and links on this project- Do you have an existing Swagger project for this?

**Comment by cherylli** [comment]
hi. yes, swagger is setup in this project, at http://www.localhost:4002/api/docs if you run the project locally

All the swagger documentations are here, https://github.com/webdev-20/shorti-url-shortener/blob/main/server/src/docs.yaml

What needs to be done is we need to add these endpoints to the existing documentation

/api/users/signup
/api/users/login

to match the code here (https://github.com/webdev-20/shorti-url-shortener/blob/main/server/src/controllers/user.controller.js)
