### ISSUE TITLE
Add Google Authentication

### ISSUE THREAD

**Issue by Ash1eyC0des** [webdev-20/shorti-url-shortener#59]
**Task**

Add passport-google-oauth20 strategy

**Comment by cherylli** [comment]
Hi @Ash1eyC0des, are you still working on this?

**Comment by Ash1eyC0des** [comment]
Hey @cherylli, sorry I'm fully involved in a job hunt right now so I don't think I will get to complete this anytime soon. Feel free to reassign if someone else wants to take the issue

**Comment by cherylli** [comment]
No problem. Good luck with your job hunt😊
