### ISSUE TITLE
Add Link/DELETE Documentation to Swagger

### ISSUE THREAD

**Issue by cherylli** [webdev-20/shorti-url-shortener#63]
Task

new endpoints which needs to be added to swagger (api/docs)
delete links
DELETE /api/links/{short}

response
"success": boolean
"message": string

More about the task (optional)
server/docs.yaml

This might be useful
https://editor.swagger.io/

**Comment by EleekaN** [comment]
Hi Cherylli, I can update it. Do I create a new branch for this?

**Comment by cherylli** [comment]
> Hi Cherylli, I can update it. Do I create a new branch for this? 

Yes please create a new branch after I merge the other pr. Thank you.
